import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    search_placeholder: "Search for articles, guides...",
    help_center: "Help Center",
    academy: "Academy",
    home: "Home",
    shortcuts: "I want to...",
    categories: "Support Categories",
    contact_support: "Still need help? Contact Support",
    sla_chat: "Live Chat (Target: < 2 mins)",
    sla_email: "Email Support (Target: < 2 hours)",
    view_article: "Read Article",
    related_articles: "Related Articles",
    web: "Web Platform",
    mobile: "Mobile App",
    requirements: "Prerequisites",
    edge_cases: "Edge Cases & Troubleshooting",
    stakes: "Why This Matters to You",
    misconceptions: "Common Misconceptions",
    regulatory_note: "Regulatory Note",
    immediate_action: "Immediate Action Required",
    evidence_checklist: "Evidence Checklist",
    investigation_timeline: "Investigation Timeline",
    possible_outcomes: "Possible Outcomes",
    search_results_for: "Search results for",
    no_results_found: "No articles found matching your query.",
    back_to_home: "Back to Home",
    last_updated: "Last updated",
    minutes_read: "min read",
    region_selector_label: "You are viewing the Global version. EU clients,",
    click_here: "click here",
    support_team_sla: "Support Team SLAs",
    theme_light: "Light",
    theme_dark: "Dark",
    how_can_we_help: "How can we help you?",
    popular: "Popular:",
    tag_withdraw: "withdraw funds",
    tag_verify: "verify identity",
    tag_mt5: "MT5 login",
    help_center_desc: "Get help fast — accounts, funding, platforms & disputes.",
    academy_desc: "Learn to trade — guided courses from basics to execution.",
    browse_support: "Browse support topics",
    view_all_articles: "View all articles",
    explore_courses: "Explore courses",
    academy_tagline: "From your first order to market microstructure — learn at your own pace.",
    still_need_help: "Still need help?",
    support_subtext: "Our support team replies in under 5 minutes, 24/5.",
    contact_support_btn: "Contact support",
    system_status: "System status",
    articles_count: "{count} articles",
    lessons_count: "{count} lessons",
    difficulty_beginner: "Beginner",
    difficulty_intermediate: "Intermediate",
    difficulty_advanced: "Advanced",
    search_category_placeholder: "Search this category...",
    popular_in_category: "Popular in this category",
    payment_methods_compared: "Payment methods compared",
    tbl_method: "Method",
    tbl_min_max: "Min / Max",
    tbl_fee: "Fee",
    tbl_processing_time: "Processing time",
    badge_fastest: "Fastest",
    related_categories: "Related categories",
    processing_times: "Processing times",
    processing_times_desc: "Deposits are usually instant. Withdrawals are reviewed within 24 hours and returned to your original payment method.",
    in_this_guide: "In this guide",
    withdrawal_sla: "Withdrawal SLA",
    sla_review_desc: "Internal review of every request.",
    sla_detail_desc: "After approval, e-wallets are instant, cards take 1–5 days, and bank wires 1–3 business days.",
    risk_note: "Risk note",
    risk_note_desc: "CFDs are leveraged products and carry a high risk of rapid loss. This lesson is educational and not investment advice. Never trade with funds you cannot afford to lose.",
    was_this_helpful: "Was this helpful?",
    yes: "Yes",
    no: "No",
    thanks_feedback: "Thanks for your feedback!",
    view_global: "view the Global version",
    sla_chat_desc: "Available 24/5 during global trading hours for immediate account resolutions.",
    sla_email_desc: "Average response under 2 hours. If it has been longer than 4 hours, please click the chat bubble for escalations.",
    risk_warning_title: "Risk Warning & Regulatory Disclosure",
    risk_warning_text_1: "Trading Forex and Contracts for Difference (CFDs) is highly speculative, carries a high level of risk, and may not be suitable for all investors. You may sustain a loss of some or all of your invested capital; therefore, you should not speculate with capital that you cannot afford to lose. Please ensure you fully understand the risks involved, taking into account your investment objectives, level of experience, and risk appetite.",
    risk_warning_text_2: "WingoMarkets does not provide investment, tax, or trading advice. WingoMarkets is a trade name under international brokerage licenses. Registration and jurisdiction rules vary by client residence. EU clients are regulated under local license regimes with restricted retail leverage up to 1:30 and negative balance protection.",
    link_privacy: "Privacy Policy",
    link_terms: "Terms & Conditions",
    link_aml: "AML Policy",
    link_disclaimer: "Risk Disclosures",
    status_all_operational: "All Systems Operational",
    status_outage: "Service Disruption",
    server_name_mt5_eu: "MT5 Server (Europe)",
    server_name_mt5_asia: "MT5 Server (Asia)",
    server_name_price_feed: "Price Feed Aggregator",
    server_name_client_portal: "Client Hub Portal",
    server_name_payment_gate: "Payment Processor Gateway",
    uptime_90_days: "90-Day Uptime History",
    operational: "Operational",
    historical_incidents: "Historical Incidents",
    resolved: "Resolved",
    incident_latency_title: "MT5 Server Latency Spike",
    incident_latency_desc: "Technical desk identified routing delays affecting order dispatch. Compliance executed audits on all pending ticket complaints during the 8-minute incident window.",
    incident_db_title: "Scheduled Database Migration",
    incident_db_desc: "Primary database clusters migrated to high-capacity nodes. No client-facing disruptions occurred.",
    incident_pay_title: "Payment Routing Lag",
    incident_pay_desc: "Routing latency on global card deposits. Client deposits successfully failover routed to backup banks within 1.5 hours.",
    form_title: "Submit a Trade Dispute Resolution Form",
    form_account: "Trading Account Number",
    form_ticket: "Trade Ticket ID",
    form_issue_type: "Issue Type",
    form_issue_slippage: "Slippage",
    form_issue_latency: "Execution Latency",
    form_issue_outage: "Server Outage",
    form_issue_pricing: "Incorrect Pricing",
    form_expected: "Expected Execution Price",
    form_actual: "Actual Filled Price",
    form_desc: "Detailed Description",
    form_submit: "Submit Dispute Ticket",
    form_success_title: "Dispute Successfully Submitted",
    form_success_desc: "Your dispute has been logged under Ticket Reference",
    form_success_sla: "Target resolution timeframe: within 24–48 hours. Our compliance desk will email you a detailed audit report.",
    step_by_step: "Step by step",
    do_this_first: "Do this first",
    what_we_need: "What we'll need from you",
    what_we_need_sub: "Please collect these details before submitting your ticket to speed up verification:",
    what_happens_next: "What happens next",
    timeline_escalate_note: "Hasn't moved past this stage?",
    timeline_escalate_link: "Here's what to do.",
    close_window: "Close Window",
    lbl_equity: "Equity",
    lbl_used_margin: "Used Margin",
    lbl_margin_level: "Margin Level",
    lbl_safe: "Safe",
    lbl_formula: "Formula",
    lbl_example_walkthrough: "Example Walkthrough",
    lbl_myth: "Myth",
    lbl_fact: "Fact",
    step_num: "Step",
    report_this_trade: "Report this trade",
    form_attached_success: "Screenshot attached successfully!",
    form_attach_prompt: "Click to attach screenshots or MT5 logs"
  },
  fa: {
    search_placeholder: "جستجو برای مقالات، راهنماها...",
    help_center: "مرکز پشتیبانی",
    academy: "آکادمی",
    home: "خانه",
    shortcuts: "می‌خواهم...",
    categories: "دسته‌بندی‌های پشتیبانی",
    contact_support: "هنوز به کمک نیاز دارید؟ تماس با پشتیبانی",
    sla_chat: "چت زنده (هدف: کمتر از ۲ دقیقه)",
    sla_email: "پشتیبانی ایمیل (هدف: کمتر از ۲ ساعت)",
    view_article: "مشاهده مقاله",
    related_articles: "مقالات مرتبط",
    web: "پلتفرم وب",
    mobile: "اپلیکیشن موبایل",
    requirements: "پیش‌نیازها",
    edge_cases: "موارد خاص و عیب‌یابی",
    stakes: "چرا این برای شما مهم است",
    misconceptions: "باورهای نادرست رایج",
    regulatory_note: "نکته مقرراتی",
    immediate_action: "اقدام فوری لازم",
    evidence_checklist: "چک‌لیست مدارک مورد نیاز",
    investigation_timeline: "زمان‌بندی بررسی",
    possible_outcomes: "نتایج احتمالی",
    search_results_for: "نتایج جستجو برای",
    no_results_found: "هیچ مقاله‌ای مطابق با جستجوی شما یافت نشد.",
    back_to_home: "بازگشت به خانه",
    last_updated: "آخرین به‌روزرسانی",
    minutes_read: "دقیقه مطالعه",
    region_selector_label: "شما در حال مشاهده نسخه جهانی هستید. مشتریان اتحادیه اروپا،",
    click_here: "اینجا کلیک کنید",
    support_team_sla: "تعهدات سطح خدمات (SLA) پشتیبانی",
    theme_light: "روشن",
    theme_dark: "تاریک",
    how_can_we_help: "چطور می‌توانیم به شما کمک کنیم؟",
    popular: "محبوب:",
    tag_withdraw: "برداشت وجه",
    tag_verify: "احراز هویت",
    tag_mt5: "ورود به متاتریدر ۵",
    help_center_desc: "دریافت سریع کمک — حساب‌ها، شارژ و برداشت، پلتفرم‌ها و اختلافات مالی.",
    academy_desc: "یادگیری معامله‌گری — دوره‌های آموزشی گام‌به‌گام از مفاهیم پایه تا اجرا.",
    browse_support: "مرور موضوعات پشتیبانی",
    view_all_articles: "مشاهده همه مقالات",
    explore_courses: "کاوش دوره‌ها",
    academy_tagline: "از اولین سفارش تا ریزساختار بازار — با سرعت خودتان یاد بگیرید.",
    still_need_help: "هنوز به کمک نیاز دارید؟",
    support_subtext: "تیم پشتیبانی ما در کمتر از ۵ دقیقه پاسخ می‌دهد، ۲۴ ساعته ۵ روز هفته.",
    contact_support_btn: "تماس با پشتیبانی",
    system_status: "وضعیت سیستم",
    articles_count: "{count} مقاله",
    lessons_count: "{count} درس",
    difficulty_beginner: "مبتدی",
    difficulty_intermediate: "متوسط",
    difficulty_advanced: "پیشرفته",
    search_category_placeholder: "جستجو در این دسته‌بندی...",
    popular_in_category: "محبوب در این دسته‌بندی",
    payment_methods_compared: "مقایسه روش‌های پرداخت",
    tbl_method: "روش پرداخت",
    tbl_min_max: "حداقل / حداکثر",
    tbl_fee: "کارمزد",
    tbl_processing_time: "زمان پردازش",
    badge_fastest: "سریع‌ترین",
    related_categories: "دسته‌بندی‌های مرتبط",
    processing_times: "زمان‌های پردازش",
    processing_times_desc: "واریزها معمولاً آنی هستند. برداشت‌ها ظرف ۲۴ ساعت بررسی شده و به روش پرداخت اولیه شما بازگردانده می‌شوند.",
    in_this_guide: "در این راهنما",
    withdrawal_sla: "تعهد زمانی برداشت",
    sla_review_desc: "بررسی داخلی برای تمامی درخواست‌ها.",
    sla_detail_desc: "پس از تأیید، کیف‌پول‌های الکترونیکی آنی، کارت‌ها ۱ تا ۵ روز و حواله‌های بانکی ۱ تا ۳ روز کاری زمان می‌برند.",
    risk_note: "هشدار ریسک",
    risk_note_desc: "قراردادهای مابه‌التفاوت (CFD) محصولات اهرمی هستند و ریسک بالایی از دست دادن سریع سرمایه را به همراه دارند. این درس صرفاً آموزشی است و توصیه سرمایه‌گذاری محسوب نمی‌شود.",
    was_this_helpful: "آیا این مقاله مفید بود؟",
    yes: "بله",
    no: "خیر",
    thanks_feedback: "از بازخورد شما متشکریم!",
    view_global: "مشاهده نسخه جهانی",
    sla_chat_desc: "در دسترس ۲۴ ساعت ۵ روز هفته در ساعات معاملاتی جهانی برای حل فوری مشکلات حساب.",
    sla_email_desc: "میانگین پاسخ‌دهی زیر ۲ ساعت. اگر بیش از ۴ ساعت طول کشیده است، لطفاً برای پیگیری روی حباب چت کلیک کنید.",
    risk_warning_title: "هشدار ریسک و افشای مقرراتی",
    risk_warning_text_1: "معامله در بازار فارکس و قراردادهای مابه‌التفاوت (CFDها) بسیار ریسک‌پذیر است و ممکن است برای همه سرمایه‌گذاران مناسب نباشد. شما ممکن است بخشی یا تمام سرمایه خود را از دست بدهید؛ بنابراین نباید با سرمایه‌ای معامله کنید که توانایی از دست دادن آن را ندارید. لطفاً اطمینان حاصل کنید که ریسک‌ها را کاملاً درک کرده‌اید.",
    risk_warning_text_2: "وینگو مارکتس هیچ‌گونه مشاوره سرمایه‌گذاری، مالیاتی یا معامله‌گری ارائه نمی‌دهد. وینگو مارکتس یک نام تجاری تحت مجوزهای کارگزاری بین‌المللی است. قوانین ثبت و صلاحیت قضایی بر اساس محل سکونت مشتری متفاوت است. اهرم مجاز برای مشتریان اتحادیه اروپا حداکثر ۱:۳۰ و برای مشتریان جهانی تا ۱:۵۰۰ است.",
    link_privacy: "سیاست حریم خصوصی",
    link_terms: "شرایط و ضوابط",
    link_aml: "قوانین ضد پولشویی",
    link_disclaimer: "افشای ریسک",
    status_all_operational: "تمامی سیستم‌ها فعال هستند",
    status_outage: "اختلال در سرویس‌دهی",
    server_name_mt5_eu: "سرور متاتریدر ۵ (اروپا)",
    server_name_mt5_asia: "سرور متاتریدر ۵ (آسیا)",
    server_name_price_feed: "سیستم قیمت‌دهی (Liquidity Feed)",
    server_name_client_portal: "پورتال کابین شخصی مشتریان",
    server_name_payment_gate: "درگاه واریز و پرداخت تراکنش‌ها",
    uptime_90_days: "سوابق پایداری سیستم در ۹۰ روز گذشته",
    operational: "فعال بدون مشکل",
    historical_incidents: "سوابق حوادث و گزارش قطعی‌ها",
    resolved: "برطرف شده",
    incident_latency_title: "نوسان تاخیر در سرور متاتریدر ۵",
    incident_latency_desc: "دپارتمان فنی تاخیری موقتی در پردازش تراکنش‌ها را شناسایی کرد. واحد انطباق لاگ‌های تمامی معاملات در آن بازه ۸ دقیقه‌ای را ممیزی کرد.",
    incident_db_title: "بروزرسانی زمان‌بندی شده دیتابیس",
    incident_db_desc: "کلاستر سرور اصلی بدون قطعی و با موفقیت ارتقا یافت. هیچ قطعی برای کاربران رخ نداد.",
    incident_pay_title: "تاخیر موقت در تایید پرداخت‌ها",
    incident_pay_desc: "بروز تاخیر در درگاه کارت‌های بین‌المللی. تراکنش‌های واریزی در مدت ۱.۵ ساعت به درگاه‌های پشتیبان هدایت شدند.",
    form_title: "فرم ثبت گزارش اختلاف معاملاتی",
    form_account: "شماره حساب معاملاتی",
    form_ticket: "شناسه تیکت معامله",
    form_issue_type: "نوع مشکل",
    form_issue_slippage: "لغزش قیمت (Slippage)",
    form_issue_latency: "تاخیر در اجرای سفارش",
    form_issue_outage: "قطعی سرور",
    form_issue_pricing: "نرخ‌گذاری اشتباه",
    form_expected: "قیمت مورد انتظار شما",
    form_actual: "قیمت نهایی اجرا شده",
    form_desc: "توضیحات تکمیلی",
    form_submit: "ارسال شکایت معامله",
    form_success_title: "شکایت معاملاتی با موفقیت ثبت شد",
    form_success_desc: "گزارش اختلاف شما با کد پیگیری زیر در سیستم ثبت شد",
    form_success_sla: "مدت زمان بررسی: ۲۴ تا ۴۸ ساعت کاری. گزارش حسابرسی دقیق لاگ‌ها به ایمیل شما ارسال خواهد شد.",
    step_by_step: "مراحل گام‌به‌گام",
    do_this_first: "ابتدا این کار را انجام دهید",
    what_we_need: "مدارک و اطلاعات مورد نیاز",
    what_we_need_sub: "لطفاً این اطلاعات را قبل از ثبت گزارش جمع‌آوری کنید تا فرآیند بررسی سریع‌تر انجام شود:",
    what_happens_next: "مراحل بعدی فرآیند بررسی",
    timeline_escalate_note: "آیا پرونده در این مرحله متوقف شده است؟",
    timeline_escalate_link: "اینجا را بخوانید.",
    close_window: "بستن پنجره",
    lbl_equity: "ارزش حساب (Equity)",
    lbl_used_margin: "مارجین مصرفی",
    lbl_margin_level: "سطح مارجین",
    lbl_safe: "امن",
    lbl_formula: "فرمول محاسبه",
    lbl_example_walkthrough: "مثال عملی",
    lbl_myth: "باور نادرست",
    lbl_fact: "واقعیت",
    step_num: "مرحله",
    report_this_trade: "گزارش این معامله",
    form_attached_success: "فایل اسکرین‌شات با موفقیت ضمیمه شد!",
    form_attach_prompt: "برای ضمیمه کردن اسکرین‌شات یا لاگ متاتریدر کلیک کنید"
  },
  ar: {
    search_placeholder: "البحث عن المقالات، الأدلة...",
    help_center: "مركز الدعم",
    academy: "الأكاديمية",
    home: "الرئيسية",
    shortcuts: "أريد أن...",
    categories: "فئات الدعم",
    contact_support: "هل ما زلت بحاجة للمساعدة؟ اتصل بالدعم",
    sla_chat: "الدردشة المباشرة (الهدف: أقل من دقيقتين)",
    sla_email: "الدعم عبر البريد الإلكتروني (الهدف: أقل من ساعتين)",
    view_article: "اقرأ المقال",
    related_articles: "مقالات ذات صلة",
    web: "منصة الويب",
    mobile: "تطبيق الهاتف",
    requirements: "المتطلبات الأساسية",
    edge_cases: "الحالات الاستثنائية وحل المشكلات",
    stakes: "لماذا يهمك هذا كمتداول",
    misconceptions: "المفاهيم الخاطئة الشائعة",
    regulatory_note: "ملاحظة تنظيمية",
    immediate_action: "إجراء فوري مطلوب",
    evidence_checklist: "قائمة التحقق من الأدلة",
    investigation_timeline: "الجدول الزمني للتحقيق",
    possible_outcomes: "النتائج المحتملة",
    search_results_for: "نتائج البحث عن",
    no_results_found: "لم يتم العثور على مقالات تطابق بحثك.",
    back_to_home: "العودة إلى الرئيسية",
    last_updated: "آخر تحديث",
    minutes_read: "دقائق قراءة",
    region_selector_label: "أنت تشاهد النسخة العالمية. لعملاء الاتحاد الأوروبي،",
    click_here: "انقر هنا",
    support_team_sla: "اتفاقية مستوى الخدمة لفريق الدعم",
    theme_light: "فاتح",
    theme_dark: "داكن",
    how_can_we_help: "كيف يمكننا مساعدتك؟",
    popular: "شائع:",
    tag_withdraw: "سحب الأموال",
    tag_verify: "تأكيد الهوية",
    tag_mt5: "تسجيل دخول MT5",
    help_center_desc: "احصل على مساعدة سريعة — الحسابات، التمويل، المنصات والنزاعات.",
    academy_desc: "تعلم التداول — دورات تعليمية موجهة من الأساسيات حتى التنفيذ.",
    browse_support: "تصفح مواضيع الدعم",
    view_all_articles: "عرض جميع المقالات",
    explore_courses: "استكشف الدورات",
    academy_tagline: "من أول صفقة لك وحتى هيكلية السوق — تعلم بالسرعة التي تناسبك.",
    still_need_help: "هل ما زلت بحاجة للمساعدة؟",
    support_subtext: "فريق الدعم لدينا يجيب في أقل من 5 دقائق، 24/5.",
    contact_support_btn: "الاتصال بالدعم",
    system_status: "حالة النظام",
    articles_count: "{count} مقال",
    lessons_count: "{count} درس",
    difficulty_beginner: "مبتدئ",
    difficulty_intermediate: "متوسط",
    difficulty_advanced: "متقدم",
    search_category_placeholder: "البحث في هذه الفئة...",
    popular_in_category: "شائع في هذه الفئة",
    payment_methods_compared: "مقارنة طرق الدفع",
    tbl_method: "الطريقة",
    tbl_min_max: "الحد الأدنى / الأقصى",
    tbl_fee: "الرسوم",
    tbl_processing_time: "وقت المعالجة",
    badge_fastest: "الأسرع",
    related_categories: "الفئات ذات الصلة",
    processing_times: "أوقات المعالجة",
    processing_times_desc: "عادة ما تكون الإيداعات فورية. تتم مراجعة السحوبات خلال 24 ساعة وإعادتها إلى طريقة الدفع الأصلية.",
    in_this_guide: "في هذا الدليل",
    withdrawal_sla: "اتفاقية سحب الأموال",
    sla_review_desc: "مراجعة داخلية لكل طلب.",
    sla_detail_desc: "بعد الموافقة، تكون المحافظ الإلكترونية فورية، وتستغرق البطاقات من 1 إلى 5 أيام، والتحويلات البنكية من 1 إلى 3 أيام عمل.",
    risk_note: "تنبيه المخاطر",
    risk_note_desc: "عقود الفروقات هي منتجات رافعة مالية وتحمل مخاطر عالية لخسارة سريعة. هذا الدرس تعليمي فقط ولا يعتبر نصيحة استثمارية.",
    was_this_helpful: "هل كان هذا مفيداً؟",
    yes: "نعم",
    no: "لا",
    thanks_feedback: "نشكرك على ملاحظاتك!",
    view_global: "مشاهدة النسخة العالمية",
    status_all_operational: "جميع الأنظمة تعمل بكفاءة",
    status_outage: "انقطاع مؤقت في الخدمة",
    server_name_mt5_eu: "سيرفر MT5 (أوروبا)",
    server_name_mt5_asia: "سيرفر MT5 (آسيا)",
    server_name_price_feed: "نظام تغذية الأسعار والسيولة",
    server_name_client_portal: "بوابة العميل وغرفة التداول",
    server_name_payment_gate: "بوابة معالجة عمليات الدفع",
    uptime_90_days: "تاريخ استقرار النظام لآخر 90 يوماً",
    operational: "يعمل بكفاءة",
    historical_incidents: "الأعطال السابقة وسجل الحوادث",
    resolved: "تم حلها",
    incident_latency_title: "تأخر مؤقت في خادم MT5",
    incident_latency_desc: "تم تحديد تأخر في معالجة الأوامر من قبل القسم الفني. تم تدقيق جميع الشكاوى المتعلقة بالصفقات في فترة الأعطال التي دامت 8 دقائق.",
    incident_db_title: "صيانة مجدولة لقاعدة البيانات",
    incident_db_desc: "تمت ترقية السيرفرات الأساسية دون أي تأثير على واجهة العميل.",
    incident_pay_title: "تأخر في معالجة المدفوعات",
    incident_pay_desc: "تأخر في معالجة بطاقات الدفع العالمية. تم تحويل الودائع تلقائياً لبنوك بديلة خلال 1.5 ساعة.",
    form_title: "نموذج تقديم شكوى تداول",
    form_account: "رقم الحساب",
    form_ticket: "معرّف تذكرة الصفقة",
    form_issue_type: "نوع المشكلة",
    form_issue_slippage: "انزلاق سعري",
    form_issue_latency: "تأخر التنفيذ",
    form_issue_outage: "انقطاع السيرفر",
    form_issue_pricing: "تسعير خاطئ",
    form_expected: "سعر التنفيذ المتوقع",
    form_actual: "سعر التنفيذ الفعلي",
    form_desc: "وصف تفصيلي",
    form_submit: "إرسال شكوى الصفقة",
    form_success_title: "تم تقديم الشكوى بنجاح",
    form_success_desc: "تم تسجيل شكواك تحت رقم مرجعي",
    form_success_sla: "الجدول الزمني للحل: خلال 24-48 ساعة. سيرسل قسم الامتثال تقرير تدقيق مفصل لبريدك الإلكتروني.",
    step_by_step: "خطوة بخطوة",
    do_this_first: "افعل هذا أولاً",
    what_we_need: "ما سنحتاجه منك",
    what_we_need_sub: "يرجى جمع هذه التفاصيل قبل تقديم التذكرة لتسريع عملية التحقق:",
    what_happens_next: "ماذا يحدث بعد ذلك",
    timeline_escalate_note: "لم تتجاوز هذه المرحلة بعد؟",
    timeline_escalate_link: "إليك ما يجب فعله.",
    close_window: "إغلاق النافذة",
    lbl_equity: "قيمة الحساب (Equity)",
    lbl_used_margin: "الهامش المستخدم",
    lbl_margin_level: "مستوى الهامش",
    lbl_safe: "آمن",
    lbl_formula: "صيغة المحاسبة",
    lbl_example_walkthrough: "مثال توضيحي",
    lbl_myth: "خرافة",
    lbl_fact: "حقيقة",
    step_num: "الخطوة",
    report_this_trade: "الإبلاغ عن هذه الصفقة",
    form_attached_success: "تم إرفاق لقطة الشاشة بنجاح!",
    form_attach_prompt: "انقر لإرفاق لقطات الشاشة أو سجلات منصة MT5"
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');
  const [dir, setDir] = useState('ltr');

  // Detect language from URL path
  const detectLanguage = (pathname) => {
    const parts = pathname.split('/');
    const locale = parts[1];
    if (['fa', 'ar'].includes(locale)) {
      return locale;
    }
    return 'en';
  };

  const updateLanguageState = (lang) => {
    setLanguage(lang);
    const direction = lang === 'en' ? 'ltr' : 'rtl';
    setDir(direction);
    document.documentElement.setAttribute('dir', direction);
    document.documentElement.setAttribute('lang', lang);
  };

  const t = (key) => {
    return translations[language][key] || translations['en'][key] || key;
  };

  const localizePath = (path) => {
    const cleanPath = path.startsWith('/') ? path : `/${path}`;
    if (language === 'en') {
      return cleanPath;
    }
    return `/${language}${cleanPath}`;
  };

  return (
    <LanguageContext.Provider value={{ language, dir, t, localizePath, updateLanguageState, detectLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
